"""Report formatter — converts scan results to various output formats.

Supports: markdown, json, sarif, html, csv
"""

import json
from typing import Dict, Any, List, Optional
from datetime import datetime, timezone


class ReportFormatter:
    """Format scan results into various output formats."""

    @staticmethod
    def to_markdown(scan_result: Dict[str, Any], title: str = "CodeMind Security Report") -> str:
        """Generate a comprehensive markdown report."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines = [
            f"# 🛡️ {title}",
            "",
            f"**Generated:** {now}",
            f"**Tool:** CodeMind v2.0.0",
            "",
            "---",
            "",
        ]

        # Executive summary
        lines.append("## 📊 Executive Summary")
        lines.append("")

        total_issues = scan_result.get("total_issues", 0)
        score = scan_result.get("score", 100)
        is_safe = scan_result.get("is_safe", True)

        status = "✅ PASSED" if is_safe else "🚨 FAILED"
        lines.append(f"| Metric | Value |")
        lines.append(f"|--------|-------|")
        lines.append(f"| **Status** | {status} |")
        lines.append(f"| **Security Score** | {score}/100 |")
        lines.append(f"| **Total Issues** | {total_issues} |")

        counts = scan_result.get("counts", {})
        if counts:
            lines.append(f"| 🔴 Critical | {counts.get('critical', 0)} |")
            lines.append(f"| 🟡 Warning | {counts.get('warning', 0)} |")
            lines.append(f"| 🔵 Info | {counts.get('info', 0)} |")

        lines.append("")

        # Security issues
        security_issues = scan_result.get("security_issues", [])
        if security_issues:
            lines.append("## 🔒 Security Issues")
            lines.append("")
            for issue in security_issues:
                sev = issue.get("severity", "info")
                emoji = {"critical": "🔴", "warning": "🟡", "info": "🔵"}.get(sev, "⚪")
                lines.append(f"### {emoji} {issue.get('message', 'Unknown issue')}")
                if issue.get("line"):
                    lines.append(f"- **Line:** {issue['line']}")
                if issue.get("snippet"):
                    lines.append(f"- **Code:** `{issue['snippet'][:80]}`")
                if issue.get("suggestion"):
                    lines.append(f"- **Fix:** {issue['suggestion']}")
                if issue.get("vulnerability_type"):
                    lines.append(f"- **Type:** {issue['vulnerability_type']}")
                lines.append("")

        # Quality issues
        quality_issues = scan_result.get("quality_issues", [])
        if quality_issues:
            lines.append("## ✨ Quality Issues")
            lines.append("")
            for issue in quality_issues:
                lines.append(f"- **Line {issue.get('line', '?')}:** {issue.get('message', '')}")
                if issue.get("suggestion"):
                    lines.append(f"  - 💡 {issue['suggestion']}")
            lines.append("")

        # Secrets
        secrets = scan_result.get("secrets", [])
        if secrets:
            lines.append("## 🔑 Secrets Detected")
            lines.append("")
            for secret in secrets:
                lines.append(f"- **Line {secret.get('line', '?')}** [{secret.get('service', 'Unknown')}]: {secret.get('message', '')}")
            lines.append("")

        # Dependencies
        dependencies = scan_result.get("dependencies", {})
        if dependencies:
            lines.append("## 📦 Dependency Vulnerabilities")
            lines.append("")
            for dep in dependencies.get("vulnerable", []):
                lines.append(f"- **{dep.get('name', '?')}** v{dep.get('version', '?')}: {dep.get('vulnerability_count', 0)} CVE(s)")
            lines.append("")

        # Footer
        lines.extend([
            "---",
            "",
            "*Generated by [CodeMind](https://codemind-ai.github.io/codemind) — The open-source security guardian for AI-generated code.*",
        ])

        return "\n".join(lines)

    @staticmethod
    def to_json(scan_result: Dict[str, Any], indent: int = 2) -> str:
        """Generate JSON report."""
        report = {
            "tool": "CodeMind",
            "version": "2.0.0",
            "generated": datetime.now(timezone.utc).isoformat(),
            **scan_result,
        }
        return json.dumps(report, indent=indent, ensure_ascii=False, default=str)

    @staticmethod
    def to_csv(scan_result: Dict[str, Any]) -> str:
        """Generate CSV report of all issues."""
        lines = ["severity,type,message,file,line,suggestion"]

        all_issues = []
        all_issues.extend(scan_result.get("security_issues", []))
        all_issues.extend(scan_result.get("quality_issues", []))

        for issue in all_issues:
            severity = issue.get("severity", "info")
            issue_type = issue.get("vulnerability_type", "quality")
            message = issue.get("message", "").replace(",", ";").replace('"', "'")
            file_path = issue.get("file", "unknown").replace(",", ";")
            line = issue.get("line", "")
            suggestion = issue.get("suggestion", "").replace(",", ";").replace('"', "'")
            lines.append(f'{severity},"{issue_type}","{message}","{file_path}",{line},"{suggestion}"')

        return "\n".join(lines)

    @staticmethod
    def to_html(scan_result: Dict[str, Any], title: str = "CodeMind Security Report") -> str:
        """Generate a standalone HTML report with embedded styles."""
        score = scan_result.get("score", 100)
        is_safe = scan_result.get("is_safe", True)
        counts = scan_result.get("counts", {})
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        score_color = "#22c55e" if score >= 90 else "#eab308" if score >= 70 else "#ef4444"
        status_text = "PASSED" if is_safe else "ISSUES FOUND"
        status_color = "#22c55e" if is_safe else "#ef4444"

        security_issues = scan_result.get("security_issues", [])
        quality_issues = scan_result.get("quality_issues", [])

        issues_html = []
        for issue in security_issues:
            sev = issue.get("severity", "info")
            sev_class = {"critical": "severity-critical", "warning": "severity-warning"}.get(sev, "severity-info")
            issues_html.append(f"""
            <tr>
                <td><span class="{sev_class}">{sev.upper()}</span></td>
                <td>{issue.get('vulnerability_type', 'Security')}</td>
                <td>{issue.get('message', '')}</td>
                <td>{issue.get('line', '-')}</td>
                <td><code>{(issue.get('snippet', '') or '')[:60]}</code></td>
                <td>{issue.get('suggestion', '-')}</td>
            </tr>""")

        for issue in quality_issues:
            sev = issue.get("severity", "info")
            sev_class = {"warning": "severity-warning"}.get(sev, "severity-info")
            issues_html.append(f"""
            <tr>
                <td><span class="{sev_class}">{sev.upper()}</span></td>
                <td>Quality</td>
                <td>{issue.get('message', '')}</td>
                <td>{issue.get('line', '-')}</td>
                <td><code>{(issue.get('snippet', '') or '')[:60]}</code></td>
                <td>{issue.get('suggestion', '-')}</td>
            </tr>""")

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               background: #0f172a; color: #e2e8f0; padding: 2rem; }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        h1 {{ font-size: 2rem; margin-bottom: 0.5rem; }}
        .subtitle {{ color: #94a3b8; margin-bottom: 2rem; }}
        .cards {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin: 2rem 0; }}
        .card {{ background: #1e293b; border-radius: 12px; padding: 1.5rem; border: 1px solid #334155; }}
        .card-label {{ color: #94a3b8; font-size: 0.875rem; text-transform: uppercase; }}
        .card-value {{ font-size: 2rem; font-weight: bold; margin-top: 0.5rem; }}
        .score-circle {{ width: 100px; height: 100px; border-radius: 50%;
                        display: flex; align-items: center; justify-content: center;
                        font-size: 1.5rem; font-weight: bold; margin: 0 auto;
                        background: conic-gradient({score_color} {score * 3.6}deg, #334155 0deg); }}
        .score-inner {{ width: 80px; height: 80px; border-radius: 50%; background: #1e293b;
                       display: flex; align-items: center; justify-content: center; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 1rem; }}
        th {{ background: #334155; padding: 0.75rem; text-align: left; font-size: 0.875rem; text-transform: uppercase; }}
        td {{ padding: 0.75rem; border-bottom: 1px solid #334155; font-size: 0.875rem; }}
        tr:hover {{ background: #1e293b; }}
        .severity-critical {{ background: #ef4444; color: white; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; }}
        .severity-warning {{ background: #eab308; color: #1e293b; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; }}
        .severity-info {{ background: #3b82f6; color: white; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; }}
        code {{ background: #334155; padding: 2px 4px; border-radius: 3px; font-size: 0.8rem; }}
        .footer {{ margin-top: 3rem; text-align: center; color: #64748b; font-size: 0.875rem; }}
        .status {{ display: inline-block; padding: 4px 12px; border-radius: 6px; font-weight: bold; 
                  background: {status_color}20; color: {status_color}; border: 1px solid {status_color}40; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🛡️ {title}</h1>
        <p class="subtitle">Generated: {now} | <span class="status">{status_text}</span></p>

        <div class="cards">
            <div class="card">
                <div class="card-label">Security Score</div>
                <div class="score-circle"><div class="score-inner" style="color: {score_color}">{score}</div></div>
            </div>
            <div class="card">
                <div class="card-label">Critical Issues</div>
                <div class="card-value" style="color: #ef4444">{counts.get('critical', 0)}</div>
            </div>
            <div class="card">
                <div class="card-label">Warnings</div>
                <div class="card-value" style="color: #eab308">{counts.get('warning', 0)}</div>
            </div>
            <div class="card">
                <div class="card-label">Total Issues</div>
                <div class="card-value">{counts.get('total', len(security_issues) + len(quality_issues))}</div>
            </div>
        </div>

        <h2 style="margin: 2rem 0 1rem">📋 Findings</h2>
        <table>
            <thead>
                <tr>
                    <th>Severity</th>
                    <th>Type</th>
                    <th>Message</th>
                    <th>Line</th>
                    <th>Code</th>
                    <th>Suggestion</th>
                </tr>
            </thead>
            <tbody>
                {''.join(issues_html) if issues_html else '<tr><td colspan="6" style="text-align: center; padding: 2rem;">✅ No issues found!</td></tr>'}
            </tbody>
        </table>

        <div class="footer">
            <p>Generated by <a href="https://codemind-ai.github.io/codemind" style="color: #60a5fa">CodeMind</a> — The open-source security guardian for AI-generated code.</p>
        </div>
    </div>
</body>
</html>"""
