"""GitHub Actions integration module.

Provides utilities for running CodeMind in GitHub Actions CI/CD pipelines.
"""

import os
from dataclasses import dataclass
from enum import Enum
from typing import Optional
from pathlib import Path


class CIEnvironment(Enum):
    """Supported CI environments."""
    GITHUB_ACTIONS = "github_actions"
    GITLAB_CI = "gitlab_ci"
    LOCAL = "local"
    UNKNOWN = "unknown"


@dataclass
class PRInfo:
    """Pull request information."""
    number: int
    title: str
    base_branch: str
    head_branch: str
    author: str
    repository: str


def detect_ci_environment() -> CIEnvironment:
    """Detect the current CI environment."""
    if os.environ.get("GITHUB_ACTIONS") == "true":
        return CIEnvironment.GITHUB_ACTIONS
    elif os.environ.get("GITLAB_CI"):
        return CIEnvironment.GITLAB_CI
    elif os.environ.get("CI"):
        return CIEnvironment.UNKNOWN
    return CIEnvironment.LOCAL


def get_pr_info() -> Optional[PRInfo]:
    """Get pull request information from CI environment."""
    env = detect_ci_environment()
    
    if env == CIEnvironment.GITHUB_ACTIONS:
        # GitHub provides PR info via GITHUB_EVENT_PATH
        event_path = os.environ.get("GITHUB_EVENT_PATH")
        if event_path and Path(event_path).exists():
            import json
            with open(event_path, "r") as f:
                event = json.load(f)
            
            pr = event.get("pull_request", {})
            if pr:
                return PRInfo(
                    number=pr.get("number", 0),
                    title=pr.get("title", ""),
                    base_branch=pr.get("base", {}).get("ref", "main"),
                    head_branch=pr.get("head", {}).get("ref", ""),
                    author=pr.get("user", {}).get("login", ""),
                    repository=os.environ.get("GITHUB_REPOSITORY", ""),
                )
    
    return None


def format_pr_comment(
    issues_critical: list[str],
    issues_warning: list[str],
    issues_info: list[str],
    files_count: int,
    lines_added: int,
    lines_deleted: int,
) -> str:
    """
    Format a PR comment with review results.
    
    Args:
        issues_critical: List of critical issues
        issues_warning: List of warning issues
        issues_info: List of info/suggestions
        files_count: Number of files changed
        lines_added: Lines added
        lines_deleted: Lines deleted
        
    Returns:
        Formatted markdown for GitHub PR comment
    """
    comment = []
    
    # Header
    comment.append("## 🧠 CodeMind Review\n")
    
    # Summary table
    comment.append("| Metric | Value |")
    comment.append("|--------|-------|")
    comment.append(f"| Files changed | {files_count} |")
    comment.append(f"| Lines | +{lines_added} / -{lines_deleted} |")
    comment.append(f"| Critical issues | {len(issues_critical)} |")
    comment.append(f"| Warnings | {len(issues_warning)} |")
    comment.append(f"| Suggestions | {len(issues_info)} |")
    comment.append("")
    
    # Critical issues
    if issues_critical:
        comment.append("### 🚨 Critical Issues\n")
        for issue in issues_critical:
            comment.append(f"- {issue}")
        comment.append("")
    
    # Warnings
    if issues_warning:
        comment.append("### ⚠️ Warnings\n")
        for issue in issues_warning:
            comment.append(f"- {issue}")
        comment.append("")
    
    # Suggestions
    if issues_info:
        comment.append("<details>")
        comment.append("<summary>💡 Suggestions</summary>\n")
        for issue in issues_info:
            comment.append(f"- {issue}")
        comment.append("</details>")
        comment.append("")
    
    # Footer
    if not issues_critical and not issues_warning:
        comment.append("✅ **No issues found!** This PR looks good.")
    elif issues_critical:
        comment.append("❌ **Action required:** Please fix critical issues before merging.")
    else:
        comment.append("⚠️ **Review recommended:** Some warnings were found.")
    
    comment.append("\n---")
    comment.append("*Generated by [CodeMind](https://github.com/codemind-ai/codemind)*")
    
    return "\n".join(comment)


def generate_workflow_file() -> str:
    """Generate a CodeMind GitHub Actions workflow file."""
    return '''name: CodeMind Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    name: AI Code Review
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install CodeMind
        run: pip install codemind
      
      - name: Run CodeMind Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get diff and generate review prompt
          codemind run --dry-run > review_prompt.txt
          
          echo "## 🧠 CodeMind Review" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Review prompt generated. See workflow logs for details." >> $GITHUB_STEP_SUMMARY
'''


def generate_action_yml() -> str:
    """Generate action.yml for GitHub Marketplace."""
    return '''name: 'CodeMind AI Review'
description: 'AI-powered code review that runs before every merge'
author: 'CodeMind Contributors'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for PR comments'
    required: true
    default: ${{ github.token }}
  fail-on-critical:
    description: 'Fail the workflow if critical issues found'
    required: false
    default: 'true'
  max-comments:
    description: 'Maximum number of review comments'
    required: false
    default: '5'

outputs:
  issues-count:
    description: 'Total number of issues found'
  critical-count:
    description: 'Number of critical issues'
  status:
    description: 'Review status (pass/fail)'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install CodeMind
      shell: bash
      run: pip install codemind
    
    - name: Run Review
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        codemind run --dry-run --preview
'''
